---
- name: Install brew packages
  community.general.homebrew:
    name:
    - bat
    - cmake
    - fzf
    - gh
    - git
    - git-delta
    - git-lfs
    - gnupg2
    - golang
    - jenv
    - jq
    - neovim
    - pass
    - pinentry-mac
    - python3
    - rbenv
    - tfenv
    - the_silver_searcher
    - tmux
    - tmux-mem-cpu-load
    - watchman
    - yh
    - zsh

- name: Install brew casks
  community.general.homebrew_cask:
    name:
    - adoptopenjdk
    - apache-directory-studio
    - aws-vpn-client
    - docker
    - mactex
    - meld
    - postman
    - session-manager-plugin
    - intellij-idea-ce
    - visual-studio-code

- name: Install brew casks
  community.general.homebrew_cask:
    name: keybase
  notify: Login to Keybase
