---
- name: Setup Basics
  hosts: all
  vars:
    user: dkub
  gather_facts: yes
  become: no
  roles:
    - role: prereqs
    - role: zsh
    - role: git
    - role: gnupg
    - role: keybase
    - role: nvim
    - role: tmux
      tags: tmux
    - role: finalize_install
