---
- name: Setup Basics
  hosts: all
  vars:
    user: dkub
  gather_facts: yes
  become: no
  roles:
    - role: dotfiles_and_software
    - role: zsh
    - role: git
    - role: gnupg
    - role: keybase
    - role: nvim
    - role: finalize_install