---
- name: Login to Keybase
  command: /usr/local/bin/keybase login
- name: Install Vim Plugins
  command: nvim +'PlugInstall --sync' +qa
- name: Install Git LFS
  command: git lfs install
  tags: [ skip_ansible_lint ] # git module does not support this command