---
- name: Detect first time
  stat:
    path: '{{ansible_user_dir}}/.config/dkub-dotfiles/dotfiles_and_software_has_run'
  register: first_run_stat

- name: Install gnu packages
  become: yes
  package:
    name:
      - pinentry-curses
      - gpg-agent
      - gpg

# GNUPG adjustments.
- name: Make sure gnupg-agent.conf exists
  file:
    path: '{{ ansible_user_dir}}/.gnupg/gpg-agent.conf'
    state: file
    mode: 'u=rw,g=,o='
- name: Ensure pinentry is configured.
  lineinfile:
    path: '{{ ansible_user_dir}}/.gnupg/gpg-agent.conf'
    regexp: '^pinentry-program'
    line: 'pinentry-program /usr/bin/pinentry'