---
- name: Check password store exists
  ansible.builtin.stat:
    path: '{{ ansible_user_dir }}/.password-store'
  register: password_store_stat
- name: Clone from keybase
  ansible.builtin.command: git clone keybase://private/dkub/pass "{{ ansible_user_dir }}/.password-store"
  when: not password_store_stat.stat.exists
  tags: [ skip_ansible_lint ] #git module does not support keybase urls.
  