---
- name: Detect first time
  stat:
    path: '{{ansible_user_dir}}/.config/dkub-dotfiles/dotfiles_and_software_has_run'
  register: first_run_stat

- name: Install fish
  become: yes
  package:
    name: fish

- name: Ensure .config dir exists
  file:
    path: '{{ ansible_user_dir }}/.config'
    state: directory

- name: Create soft links to place configurations
  file:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    state: link
    force: yes
  with_items:
    - src: '{{ ansible_user_dir }}/.dotfiles/fish'
      path: '{{ ansible_user_dir }}/.config/fish'
    - src: '{{ ansible_user_dir }}/.dotfiles/omf'
      path: '{{ ansible_user_dir }}/.config/omf'

## Oh my fish
- name: Check oh my fish exists
  stat:
    path: '{{ ansible_user_dir }}/.local/share/omf'
  register: stat_ohmyfish_result

- name: Get oh my fish script
  get_url:
    url: https://get.oh-my.fish
    dest: /tmp/install_omf.fish
  when: not stat_ohmyfish_result.stat.exists

- name: Install oh my fish
  command: /usr/bin/fish /tmp/install_omf.fish --noninteractive
  when: not stat_ohmyfish_result.stat.exists

- name: Set fish as default shell for {{ user }}
  become: yes
  user:
    name: "{{ user }}"
    shell: /usr/bin/fish
