---
- name: Detect first time
  ansible.builtin.stat:
    path: '{{ansible_user_dir}}/.config/dkub-dotfiles/dotfiles_and_software_has_run'
  register: first_run_stat

- name: Install prerequistes
  community.general.homebrew:
    name:
      - tmux

- name: Link tmux.conf
  ansible.builtin.file:
    path: '{{ ansible_user_dir}}/.tmux.conf'
    src: '{{ ansible_user_dir}}/.dotfiles/tmux/tmux.conf'
    state: link

- name: Install tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: '{{ ansible_user_dir}}/.tmux/plugins/tpm'
  notify: Install tpm Plugins

- name: Detect xterm-256color-italic terminal type
  ansible.builtin.shell:
    cmd: find {{ ansible_user_dir }}/.terminfo -type f -name 'xterm-256color-italic' | grep .
  register: italic_term_installed
  ignore_errors: yes #Non-zero is kinda actually what we are looking for.

- name: Install xterm-256color-italic terminal type
  ansible.builtin.shell:
    cmd: tic -x {{ role_path }}/resources/xterm-256color-italic.terminfo
  when: italic_term_installed.rc != 0

- name: Detect tmux-256color-italic terminal type
  ansible.builtin.shell:
    cmd: find {{ ansible_user_dir}}/.terminfo -type f -name 'tmux-256color-italic' | grep .
  register: tmux_term_installed
  ignore_errors: yes #Non-zero is kinda actually what we are looking for.

- name: Install tmux-256color terminal type
  ansible.builtin.shell:
    cmd: tic -x {{ role_path }}/resources/tmux-256color-italic.terminfo
  when: tmux_term_installed.rc != 0
