---
- name: Link iTerm2 Profiles
  file:
    path: '{{ ansible_user_dir }}/Library/Preferences/com.googlecode.iterm2.plist'
    src: '{{ ansible_user_dir }}/.dotfiles/iterm2/com.googlecode.iterm2.plist'
    state: link
    force: yes