---
- name: Tap cask fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present
- name: Install fonts
  community.general.homebrew_cask:
    name:
      - font-fira-code-nerd-font
      - font-mononoki-nerd-font
      - font-meslo-lg-nerd-font
    state: present
